Report buttles on block creation events

diff --git a/publish-pool-slots b/publish-pool-slots
--- a/publish-pool-slots
+++ b/publish-pool-slots
@@ -5,8 +5,8 @@
 
 function showHelp() {
     cat <<EOF
-usage: $(basename $0) [-i INTERVAL] [-e ENCLAVE] [-d] [-C] [-S] [-E]
-          [-a TELEGRAM_ACCESS_TOKEN] [-c CHANNEL_ID] [-n HEADER]
+usage: $(basename $0) [-i INTERVAL] [-e ENCLAVE] [-d] [-C] [-S] [-E] [-F]
+          [-a TELEGRAM_ACCESS_TOKEN] [-c CHANNEL_ID] [-n HEADER] [-f FILE]
           [-L LOG_LEVEL] [-j] [-h]
   -i  Interval that will be used for regular checking.
       If not specified then send info only once and exit.
@@ -18,12 +18,16 @@ usage: $(basename $0) [-i INTERVAL] [-e ENCLAVE] [-d] [-C] [-S] [-E]
   -C  Do not report count of slots for an epoch.
   -S  Do not include into the report the slots schedule.
   -E  Do not report block creation events.
+  -F  Do not report block creation competition buttles info. This option is assumed when path to
+      \`blocks.sqlite\` is not defined (option \`-f\` is not defined).
   -a  Bot access token. If not specified then environment variable with name \`TELEGRAM_BOT_AUTH_TOKEN\`
       will be used for authentication. If none specified then telegram output will not be used.
   -c  Telegram channel to which send messages. E.g. \`@CardanoNodesHeartbeat\`. You can specify this option
       several times to send message to several channels.
   -n  Pool name/identifier. You can use the ticker of your pool here.
       If defined it will be the first line of every telegram message.
+  -f  Path to \`blocks.sqlite\` file with blockchain database. Mandatory if competition buttles info needed
+      in report.
   -L  Log level. One of the values \`error\`, \`warn\`, \`info\`, \`debug\`, \`trace\`. Only messages with
       this and stronger severity level will be logged.
   -j  Prepare messages for journald severity levels.
@@ -43,7 +47,7 @@ T_CHANNEL_IDS=()
 # Access token for Telegram Bot API
 T_AUTH_TOKEN=$TELEGRAM_BOT_AUTH_TOKEN
 
-while getopts 'e:n:i:a:c:L:CSEdjh' c
+while getopts 'e:n:i:a:c:f:L:CSEFdjh' c
 do
     case $c in
         e) if ! is_number "$OPTARG"; then
@@ -62,6 +66,13 @@ do
            ;;
         a) T_AUTH_TOKEN="$OPTARG" ;;
         c) T_CHANNEL_IDS[${#T_CHANNEL_IDS[*]}]="$OPTARG" ;;
+        f) DB_FILE_NAME="$OPTARG"
+           if ! [ -f "$DB_FILE_NAME" ]; then
+               logError 'Wrong value for option `-f`' >&2
+               showHelp >&2
+               exit 1
+           fi
+           ;;
         L) if ! parseLogLevel $OPTARG; then
                logError 'Wrong value for option `-L`' >&2
                showHelp >&2
@@ -73,11 +84,18 @@ do
         C) WO_SLOTS_COUNT=1;;
         S) WO_SCHEDULE_TIMES=1;;
         E) WO_BLOCK_CREATION_EVENTS=1;;
+        F) WO_BLOCK_CREATION_COMPETITION=1;;
         h) showHelp; exit 0 ;;
         ?) showHelp >&2; exit 1;;
     esac
 done
 
+if [ -z "$DB_FILE_NAME" ]; then
+    WO_BLOCK_CREATION_COMPETITION=1
+fi
+
+
+readonly ENOUGH_CONFIRMATION_COUNT=10
 
 CURRENT_EPOCH=
 CURRENT_EPOCH_BLOCK_COUNT=
@@ -178,6 +196,118 @@ function getNewBlocks {
 '
 }
 
+function isEnoughConfirmationCount {
+    local block="$1"
+
+    local confirmation_count ERR_MSG
+    catch confirmation_count ERR_MSG "curl -sSf $JORMUNGANDR_RESTAPI_URL/v0/block/$block/next_id?count=$ENOUGH_CONFIRMATION_COUNT | xxd -p -c32 | wc -l"
+    if [ -n "$ERR_MSG" ] && ! isNotFoundMessage "$ERR_MSG"; then
+        logError "$ERR_MSG" >&2
+    fi
+    (( confirmation_count >= ENOUGH_CONFIRMATION_COUNT )) && return 0 || return $confirmation_count
+}
+
+function getHeightCompetition {
+    local dbFile=$1
+    local checkHeight=$2
+    local ___BLOCK_IDS=$(echo "$3" | cut -d. -f1)
+    local ___POOL_IDS=$(echo "$3" | cut -d. -f2)
+    local ___EPOCHS=$(echo "$3" | cut -d. -f3)
+    local ___SLOTS=$(echo "$3" | cut -d. -f4)
+    local ___WINNER=$(echo "$3" | cut -d. -f5)
+
+    local sql1="
+select * from (
+select hex(bi.hash) as hash
+     , (
+          with unhex(val, s_, w_) as (
+            select 0 as val, substr(hex(b.block),17,8) as s_, 1 as w_
+            union all
+            select val + (instr('0123456789ABCDEF', substr(s_, length(s_), 1)) - 1) * w_ as val
+                 , substr(s_, 1, length(s_) - 1) as s_
+                 , w_ * 16 as w_
+            from unhex where length(s_) > 0
+          )
+          select val from unhex order by w_ desc limit 1
+       ) as epoch
+     , (
+          with unhex(val, s_, w_) as (
+            select 0 as val, substr(hex(b.block),25,8) as s_, 1 as w_
+            union all
+            select val + (instr('0123456789ABCDEF', substr(s_, length(s_), 1)) - 1) * w_ as val
+                 , substr(s_, 1, length(s_) - 1) as s_
+                 , w_ * 16 as w_
+            from unhex where length(s_) > 0
+          )
+          select val from unhex order by w_ desc limit 1
+       ) as slot
+     , substr(hex(b.block),169,64) as pool
+  from BlockInfo bi
+  join Blocks b on b.hash = bi.hash
+ where bi.depth = ${checkHeight}
+)
+order by epoch, slot, pool
+    "
+
+    local idx=0
+    for record in $(echo "$sql1" | sqlite3 $dbFile -list)
+    do
+        local block=$(echo -n $record | cut -d'|' -f1 | toLower)
+        local epoch=$(echo -n $record | cut -d'|' -f2)
+        local slot=$(echo -n $record | cut -d'|' -f3)
+        local pool=$(echo -n $record | cut -d'|' -f4 | toLower)
+        [ -n "$___BLOCK_IDS" ] && eval "$___BLOCK_IDS[$idx]='$block'"
+        [ -n "$___POOL_IDS" ] && eval "$___POOL_IDS[$idx]='$pool'"
+        [ -n "$___EPOCHS" ] && eval "$___EPOCHS[$idx]='$epoch'"
+        [ -n "$___SLOTS" ] && eval "$___SLOTS[$idx]='$slot'"
+        if [ -n "$___WINNER" ]; then
+            if isEnoughConfirmationCount "$block"; then
+                eval "$___WINNER='$block'"
+            fi
+        fi
+        (( idx += 1 ))
+    done
+
+}
+
+function printCompetitiveButtles {
+    local SIMPLE_LOGGING=$1
+    local withWinnerSelection=${2:-no}
+    local blockJson=$3
+
+    if [ -z "$WO_BLOCK_CREATION_COMPETITION" ]; then
+        local BLOCK_ID=$(echo -n $blockJson | jq -rc '.status.Block.block')
+        local HEIGHT=$(echo -n $blockJson | jq -rc '.status.Block.chain_length + 1')
+
+        local -a BLOCK_IDS=()
+        local -a POOL_IDS=()
+        local -a EPOCHS=()
+        local -a SLOTS=()
+        local WINNER
+        getHeightCompetition "$DB_FILE_NAME" "$HEIGHT" "BLOCK_IDS.POOL_IDS.EPOCHS.SLOTS$([ "$withWinnerSelection" == "yes" ] && echo -n ".WINNER")"
+
+        local oncePassed=no
+        for i in "${!BLOCK_IDS[@]}"
+        do
+            if [ "${BLOCK_IDS[$i]}" != "$(toLower "$BLOCK_ID")" ]; then
+                local block_id="${BLOCK_IDS[$i]}"
+                local pool_id="${POOL_IDS[$i]}"
+                local epoch="${EPOCHS[$i]}"
+                local slot="${SLOTS[$i]}"
+                if [ "$SIMPLE_LOGGING" == "yes" ]; then
+                    [ "$oncePassed" == "no" ] && logNotice "\nThere were competitors at the height:"
+                    logNotice "  Pool <a href=\"https://shelleyexplorer.cardano.org/en/stake-pool/$pool_id\">$(shortenId "$pool_id" 4)</a> with slot $([ "$WINNER" == "$block_id" ] && echo -n "<a href=\"https://shelleyexplorer.cardano.org/en/block/$block_id\">")<b><i>$epoch.$slot</i></b>$([ "$WINNER" == "$block_id" ] && echo -n '</a>')"
+                else
+                    [ "$oncePassed" == "no" ] && logNotice "  There were competitors at height $HEIGHT:"
+                    logNotice "    Pool $pool_id with slot $epoch.$slot"$([ "$WINNER" == "$block_id" ] && echo -n " and block $block that won.")
+                fi
+                oncePassed=yes
+            fi
+        done
+
+    fi
+}
+
 function printBlockSuccess {
     local SIMPLE_LOGGING=$1
     local blockJson=$2
@@ -188,8 +318,10 @@ function printBlockSuccess {
 
     if [ "$SIMPLE_LOGGING" == "yes" ]; then
         logNotice "Slot <b><i>$SLOT</i></b> $(qs)SUCCEEDED$(qe): block <a href=\"https://shelleyexplorer.cardano.org/en/block/$BLOCK_ID\">$BLOCK_ID</a> was successfully produced at height <b><i>$HEIGHT</i></b>."
+        printCompetitiveButtles yes no "$blockJson"
     else
         logNotice "Slot $SLOT SUCCEEDED: block $BLOCK_ID was successfully produced at height $HEIGHT."
+        printCompetitiveButtles no no "$blockJson"
     fi
 }
 
@@ -202,9 +334,11 @@ function printBlockFailFork {
     local HEIGHT=$(echo -n $blockJson | jq -rc '.status.Block.chain_length + 1')
 
     if [ "$SIMPLE_LOGGING" == "yes" ]; then
-        logNotice "Slot <b><i>$SLOT</i></b> $(qs)FAILED$(qe): block <a href=\"https://shelleyexplorer.cardano.org/en/block/$BLOCK_ID\">$BLOCK_ID</a> at height <b><i>$HEIGHT</i></b> got into a competitive fork that lost."
+        logNotice "Slot <b><i>$SLOT</i></b> $(qs)FAILED$(qe): block <b><i>$BLOCK_ID</i></b> at height <b><i>$HEIGHT</i></b> got into a competitive fork that lost."
+        printCompetitiveButtles yes yes "$blockJson"
     else
         logNotice "Slot $SLOT FAILED: block $BLOCK_ID at height $HEIGHT got into a competitive fork that lost."
+        printCompetitiveButtles no yes "$blockJson"
     fi
 }
 
@@ -228,21 +362,20 @@ function makeOneCreatedBlockReport {
     local lastBlockHeight=$1
     local blockJson=$2
 
-    local enough_confirmation_count=10
     local block=$(echo -n "$blockJson" | jq -rc '.status.Block?.block')
     if [ -n "$block" ] && [ "null" != "$block" ]; then
         local confirmation_count ERR_MSG
-        catch confirmation_count ERR_MSG "curl -sSf $JORMUNGANDR_RESTAPI_URL/v0/block/$block/next_id?count=$enough_confirmation_count | xxd -p -c32 | wc -l"
+        catch confirmation_count ERR_MSG "curl -sSf $JORMUNGANDR_RESTAPI_URL/v0/block/$block/next_id?count=$ENOUGH_CONFIRMATION_COUNT | xxd -p -c32 | wc -l"
         if [ -n "$ERR_MSG" ] && ! isNotFoundMessage "$ERR_MSG"; then
             logError "$ERR_MSG" >&2
         fi
-        if (( confirmation_count >= enough_confirmation_count )); then
+        if (( confirmation_count >= ENOUGH_CONFIRMATION_COUNT )); then
             printBlockSuccess "no"  "$blockJson"
             printBlockSuccess "yes" "$blockJson" | sendToTelegram
             return 0
         else
             local blockHeight=$(echo -n "$blockJson" | jq -rc '.status.Block?.chain_length + 1')
-            if (( (confirmation_count + blockHeight) < (lastBlockHeight - enough_confirmation_count) )); then
+            if (( (confirmation_count + blockHeight) < (lastBlockHeight - ENOUGH_CONFIRMATION_COUNT) )); then
                 # this block in a fork
                 printBlockFailFork "no" "$blockJson"
                 printBlockFailFork "yes" "$blockJson" | sendToTelegram
