fixup! Utility for publishing statistics to `pooltool.io`
fix: Report count of slots only on epoch change, not at start.

diff --git a/publish-to-pooltool b/publish-to-pooltool
--- a/publish-to-pooltool
+++ b/publish-to-pooltool
@@ -23,6 +23,8 @@ usage: $(basename $0) [-i INTERVAL] [-p POOLID] [-u USERID] [-g GENESISPREF] [-e
   -L  Log level. One of the values \`error\`, \`warn\`, \`info\`, \`debug\`, \`trace\`. Only messages with
       this and stronger severity level will be logged.
   -j  Prepare messages for journald severity levels.
+  -c  Count of blocks to publish. If this option is specified then only report this count of slots for
+      the current epoch.
   -h  Show this help.
 
 This scrip send information about slots count to pooltool.io statistics service.
@@ -34,7 +36,7 @@ EOF
 
 POOLTOOL_USER_ID=$POOLTOOL_API_KEY
 
-while getopts 'i:p:u:g:e:L:CTBjh' c
+while getopts 'i:p:u:g:e:c:L:CTBjh' c
 do
     case $c in
         i) INTERVAL=$(printf "%s" $OPTARG | parseInterval)
@@ -53,6 +55,12 @@ do
                exit 1
            fi
            ENCLAVE_LEADER_ID="$OPTARG" ;;
+        c) if ! is_number "$OPTARG"; then
+               logError 'Wrong value for option `-c`' >&2
+               showHelp >&2
+               exit 1
+           fi
+           MANUAL_SLOTS_COUNT="$OPTARG";;
         L) if ! parseLogLevel $OPTARG; then
                logError 'Wrong value for option `-L`' >&2
                showHelp >&2
@@ -80,6 +88,20 @@ if [ -z "$GENESISPREF" ]; then
     logError 'Option `-g` is mandatory' >&2
     show_help=yes
 fi
+if [ -n "$MANUAL_SLOTS_COUNT" ]; then
+    if [ -n "$INTERVAL" ]; then
+        logError 'Options `-c` and `-i` are mutually exclusive' >&2
+        show_help=yes
+    fi
+    if [ -n "$WO_SLOTS_COUNT_REPORT" ]; then
+        logError 'Options `-c` and `-C` are mutually exclusive' >&2
+        show_help=yes
+    fi
+    if [ -n "$ENCLAVE_LEADER_ID" ]; then
+        logError 'Options `-c` and `-e` are mutually exclusive' >&2
+        show_help=yes
+    fi
+fi
 if [ -n "$show_help" ]; then
     showHelp >&2
     exit 1
@@ -88,8 +110,8 @@ fi
 
 CURRENT_EPOCH=
 CURRENT_EPOCH_BLOCK_COUNT=
+LAST_EPOCH=
 LAST_REPORTED_EPOCH=
-LAST_EPOCH_THAT_CAME=
 LAST_SLOTS_COUNT_REPORT_TRY_TIME=
 
 function fetchNodeStats {
@@ -229,26 +251,34 @@ function doOnce {
     fi
     local epoch=$(echo -n $nodeStatsJson | getCurrentEpoch)
     if is_number $epoch; then
-        if [ -z "$WO_SLOTS_COUNT_REPORT" ]; then
-            if (( $epoch > ${LAST_REPORTED_EPOCH:-0} )); then
-                if (( $epoch > ${LAST_EPOCH_THAT_CAME:-0} )); then
-                    sleep 11 # After epoch change wait a little to not overload polltool service as everybody will proceed this time
-                    LAST_EPOCH_THAT_CAME=$epoch
-                fi
-                local currentTime=$(date +%s)
-                if (( $currentTime > (${LAST_SLOTS_COUNT_REPORT_TRY_TIME:-0} + 300) )); # Try not more than once every 5 minutes
-                then
-                    local slotsCount=$(fetchLeadersLogs | getSlotsCountForEpoch "$epoch")
-                    if is_number $slotsCount; then
-                        LAST_SLOTS_COUNT_REPORT_TRY_TIME=$(date +%s)
-                        sendSlotsCountToPooltool $epoch $slotsCount && \
-                            LAST_REPORTED_EPOCH="$epoch"
-                    else
-                        logError "Cannot get count of slots" >&2
+        if [ -n "$MANUAL_SLOTS_COUNT" ]; then
+            sendSlotsCountToPooltool $epoch $MANUAL_SLOTS_COUNT
+            exit 0
+        elif [ -z "$WO_SLOTS_COUNT_REPORT" ] ; then
+            if [ -n "$LAST_REPORTED_EPOCH" ]; then
+                if (( $epoch > $LAST_REPORTED_EPOCH )); then
+                    sleep 11 # After epoch change wait a little to not overload pooltool service as everybody will proceed this time
+                    local currentTime=$(date +%s)
+                    if (( $currentTime > (${LAST_SLOTS_COUNT_REPORT_TRY_TIME:-0} + 300) )); # Try not more than once every 5 minutes
+                    then
+                        local slotsCount=$(fetchLeadersLogs | getSlotsCountForEpoch "$epoch")
+                        if is_number $slotsCount; then
+                            LAST_SLOTS_COUNT_REPORT_TRY_TIME=$(date +%s)
+                            sendSlotsCountToPooltool $epoch $slotsCount && \
+                                LAST_REPORTED_EPOCH="$epoch"
+                        else
+                            logError "Cannot get count of slots" >&2
+                        fi
                     fi
                 fi
+            else
+                # Report onlly when epoch changed. Do not report the state at start timea as the leaders logs
+                # contain all allocated blocks with sure only at the epoch beginning time.
+                LAST_REPORTED_EPOCH=$epoch
             fi
         fi
+        LAST_EPOCH=$epoch
+
         if [ -z "$WO_TIP_REPORT" ]; then
             sendTipToPoolTool "$nodeStatsJson"
         fi
